### ISSUE TITLE
Crash: `java.lang.IllegalArgumentException`

### ISSUE THREAD

**Issue by himea-saito** [Krutoy242/Enigmatica2Expert-Extended#152]
## Description

Player used random teleport command to a new location, this location seems to cause the server to crash upon being loaded in. I had to edit the player's location and move them away from the location in question to get the server in a running state, else it would immediately crash upon player login.

**To Reproduce**

1. Navigate to the following coordinates with seed 6939426724564089242: -22032x, 73y, -47185
2. Cause the chunk to be loaded by having a player present
3. See error

```less
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// I blame Dinnerbone.

Time: 2023-01-15 19:04:15 UTC
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Waila (waila)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:899)
    at java.util.TimSort.mergeAt(TimSort.java:516)
    at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
    at java.util.TimSort.sort(TimSort.java:254)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.ArrayList.sort(ArrayList.java:1464)
    at mcp.mobius.waila.proxy.ProxyCommon.loadComplete(ProxyCommon.java:64)
    at mcp.mobius.waila.Waila.loadComplete(Waila.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 5.4.0-128-generic
  Java Version: 1.8.0_292, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
  Memory: 4949404080 bytes (4720 MB) / 7893680128 bytes (7528 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 19 total; -Xmx8192M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2860 396 mods loaded, 395 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
```

Full report too large, added as file:
[crash-2023-01-15_19.04.15-server.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/10421040/crash-2023-01-15_19.04.15-server.txt)

**Modpack version** `v0.88.0`

**`debug.log`:
[2023-01-15-3.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/10421043/2023-01-15-3.log)

**Comment by Krutoy242** [comment]
This is possibly caused by `Waila` mod.

If you have time, please remove Waila (with its addons) from server and try to reproduce error again. As i recall, its called `Hwyla-1.8.26-B41_1.12.2.jar`.
Probably, you would need to remove Waila from client too, but not sure.

Secondary, Waila most likely cant be reason of actual crash. Considering your `debug.log` have this line, its probably related to world generation - maybe something huge trying to generate in this place, so its hang more then 60 seconds.
```less
A single server tick took 60.00 seconds (should be max 0.05)
Considering it to be crashed, server will forcibly shutdown.
```

You can try to higher value in your `server.properties` file `max-tick-time=240000`

P.S. I cannot reproduce the issue, but thank you for cite steps anyway 
![image](https://user-images.githubusercontent.com/936618/212567203-25aa9dc8-98be-41f7-81ee-b5fff41f8a54.png)

**Comment by himea-saito** [comment]
> This is possibly caused by `Waila` mod.
> 
> If you have time, please remove Waila (with its addons) from server and try to reproduce error again. As i recall, its called `Hwyla-1.8.26-B41_1.12.2.jar`. Probably, you would need to remove Waila from client too, but not sure.
> 
> Secondary, Waila most likely cant be reason of actual crash. Considering your `debug.log` have this line, its probably related to world generation - maybe something huge trying to generate in this place, so its hang more then 60 seconds.
> 
> ```css-less
> A single server tick took 60.00 seconds (should be max 0.05)
> Considering it to be crashed, server will forcibly shutdown.
> ```
> 
> You can try to higher value in your `server.properties` file `max-tick-time=240000`
> 
> P.S. I cannot reproduce the issue, but thank you for cite steps anyway ![image](https://user-images.githubusercontent.com/936618/212567203-25aa9dc8-98be-41f7-81ee-b5fff41f8a54.png)

Thank you, I will try increasing the timeout period and try again!

**Comment by himea-saito** [comment]
Just a follow-up, it does appear that increasing the timeout for the server has helped with crashes. 

This issue is difficult to reproduce precisely, but the fault seems to be mazes that generate underground can sometimes take a lot of processing power to generate and lock up the server for a good chunk of time. Flying around in creative mode had me encounter a couple of these moments, but after setting the time-out to three minutes, I wasn't able to reproduce the crash so I believe that was the issue.
