### ISSUE TITLE
Crash: `NoSuchMethodError: com.pg85.otg.forge.dimensions.OTGDerivedWorldInfo.func_76092_g()J`

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [Krutoy242/Enigmatica2Expert-Extended#205]
## Description
Modpack almost entirely loads, crashes at the very end.

**To Reproduce**
Start the modpack using `./ServerStartLinux.sh`

**Modpack version** `v1.1.0 Skyblock confirmed`

**Crash report**
``` log
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// There are four lights!

Time: 2023-04-18 20:02:37 UTC
Description: Exception in server tick loop

java.lang.NoSuchMethodError: com.pg85.otg.forge.dimensions.OTGDerivedWorldInfo.func_76092_g()J
    at com.pg85.otg.forge.dimensions.OTGDerivedWorldInfo.updateTagCompound(OTGDerivedWorldInfo.java:56)
    at com.pg85.otg.forge.dimensions.OTGDerivedWorldInfo.cloneNBTCompound(OTGDerivedWorldInfo.java:39)
    at fi.dy.masa.justenoughdimensions.util.world.WorldFileUtils.saveWorldInfoToFile(WorldFileUtils.java:342)
    at fi.dy.masa.justenoughdimensions.util.world.WorldFileUtils.saveCustomWorldInfoToFile(WorldFileUtils.java:395)
    at fi.dy.masa.justenoughdimensions.event.JEDEventHandler.onWorldSave(JEDEventHandler.java:173)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2513_JEDEventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
    at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:395)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 5.15.0-69-generic
  Java Version: 1.8.0_362, Private Build
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
  Memory: 2657309192 bytes (2534 MB) / 4001366016 bytes (3816 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 19 total; -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
  IntCache: cache: 3, tcache: 104, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2860 395 mods loaded, 394 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
```

**Comment by Krutoy242** [comment]
Thank you for report, I will investigate the issue.
